package:
  name: pear
  version: '0.9.11'

about:
  home: http://sco.h-its.org/exelixis/web/software/pear/
  license: 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported'
  summary: 'paired-end read merger'

source:
  sha256: 311c5c34ab27ae2301b8135182ee95b5c92010dcc903d01d658c9870e3ae4728
  url: https://github.com/ressy/pear/archive/refs/tags/v0.9.11.tar.gz

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - make
    - {{ compiler('gcc') }}
    - pkgconfig
    - zlib
  host:
    - zlib
    - bzip2
  run:
    - zlib
    - bzip2

test:
  commands:
    - pear 2>&1 | grep "PEAR v0.9.11"
    - pearRM 2>&1 | grep "PEAR v0.9.11"

extra:
  identifiers:
    - biotools:PEAR
